[image] Updates/fixes
activeshadow/phenix pull request #36
Opened 2021-02-10 17:55 UTC by glattercj

Add POSTBUILD_GUI script. Remove kali from variants in comments. Add no_root, base, and hostname scripts to brash variant.

2021-02-24 15:42 UTC, activeshadow requested changes

2021-02-24 15:42 UTC, activeshadow commented on src/go/api/image/image.go
>  	case "brash":
Does it make sense to even have the `brash` option anymore in this version of phenix?

2021-02-24 15:42 UTC, activeshadow commented on src/go/api/image/image.go
> +	img.Scripts = make(map[string]string)
I wonder if it makes more sense to move this to the `addScriptToImage` function and check to see if `img.Scripts == nil` before adding to it.

2021-02-24 15:42 UTC, activeshadow commented on src/go/api/image/constants.go
>  const POSTBUILD_PROTONUKE = `
I wonder if we should take this POSTBUILD out and let the protonuke app handle it. Probably something for a different PR.

2021-02-24 15:45 UTC, glattercj commented on src/go/api/image/constants.go
>  const POSTBUILD_PROTONUKE = `
Probably, if we want to keep these more generic.

2021-02-24 19:38 UTC, glattercj commented on src/go/api/image/image.go
>  	case "brash":
I went back and forth on this. I suppose it makes more sense to add the scripts directly to the specific image when we create it, rather than having it be a variant and automatically adding them in the main src.

2021-02-25 16:51 UTC, activeshadow commented on src/go/api/image/image.go
>  	case "brash":
Can you work on taking all the `brash` stuff out?

2021-02-25 16:54 UTC, activeshadow commented on src/go/api/image/image.go
> +	img.Scripts = make(map[string]string)
This is not a show stopper for now.

2021-03-17 15:23 UTC, glattercj commented on src/go/api/image/image.go
>  	case "brash":
Done. Might want to check the `image_test` to make sure it still works.

2021-04-13 16:36 UTC, activeshadow approved these changes
LGTM

2021-04-13 17:48 UTC, merged